### ISSUE TITLE
レンダリングエンジン「Safari」？

### ISSUE THREAD

**Issue by iciclize** [piroor/moezilla-memorial-photobook#2]
面白い記事を読ませていただきました。ありがとうございます。
「WebKitとChromeの登場」の章の `レンダリングエンジン「Safari」` は `レンダリングエンジン「WebKit」` の typo でしょうか？

```
その成果がレンダリングエンジン「Safari」であり、2003年にリリースされたApple自社ブランドのWebブラウザー「Safari」でした。
```

**Comment by piroor** [comment]
ご指摘ありがとうございます。こちらは確かにtypoでした。
403cb77 で修正しました。
