### ISSUE TITLE
校正

### ISSUE THREAD

**Issue by hokonch** [piroor/moezilla-memorial-photobook#3]
> 雑な書き方をしといた方が「はあ？ 何偉そうに語ってくれてんのこいつ？」と識者から校閲してもらえるんじゃないかというテスト。
> したり顔で語られる嘘・大げさ・紛らわしい表現をぶっ叩くチャンスですよあげ
https://twitter.com/piro_or/status/1631222342658723840

にわかFirefoxファンでしかないので古い話の校閲はできませんが、勉強がてら校正してみました

https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L53
一部して→一部として
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L92
音して→落として
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L102
トーバルス→トーバルズ
再配付→再配布
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L171
Office 365→Microsoft 365
Microsoft 365はWebアプリのみではないと思うので、少々違和感があります
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L269
現在は、Firefox、Thunderbirdの名前で収録されています。
また、
Debian、Firefoxのロゴが非互換なライセンスだったため、Mozillaの了承のもと独自のアイコンに差し替え
↓
Mozilla、方針を変更し、正規のロゴを使い改変をレビューさせないと、Firefoxという商標は使わせないとDebianに通告
↓
Debian、非互換ライセンスのロゴはfreeリポジトリに収録できないので、名称変更
↓
Mozilla、ロゴのライセンスを互換性あるよう変更
↓
Mozilla、Debianによる改変は信用する、名前を元に戻せとリクエスト

という流れのようですから、「商標がポリシーに反していた」と読める文章は、この要約としては誤りかなと思います。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L303
個人的にはFirefox for Android はしばらくFlash使えてたような…と少し混乱しました。「PC以外」より具体的に書くほうが親切かもしれません。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L351
ACID2→Acid2 
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L507
今の訳語は「トラッキング防止」です。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L532
Fenix移行前のFennecはネイティブUIだったと思います。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L534
Fenixリリース直後からWebExtensions API（の必要な一部）は実装されていました。自由なインストールは今も認められていません。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L538
2台巨頭→2大巨頭
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L545
Firefox OS 直後のB2Gならコミュニティベースでしょうが、KaiOSは企業製では？と思いました。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L643
中かで→中で
また、Waterfox自体はレガシーアドオン廃止前からあったのでは、と思いました。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L668
Servoも「Mozillaの傘下を離れて独立したプロジェクト」ですね。最近Igaliaをバックにしたプロジェクト再始動が発表されています。

https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L697
ざっくり標準化団体の資料を読んだ感じ、3つではなさそうです
WHATWG: 2つの支持
w3c:　十分な実装経験（相互運用性ある複数の実装の存在が望ましい）
TC39:　2つの実装
身も蓋もないはなしで言えば、一番よく言われるのは、反トラスト法だと思いますが…

https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L698
 Mozilla Foundationには→Mozillaに
「は」が余計なのと、おそらくGoogleとアフィリエイト契約結んでいるのはMoCoの方です

https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L726
ザーバー→サーバー
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L739
難度→何度
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L782
資金的には既に独立しているという認識で、MZLAがMozillaから独立するという話があるということでしょうか。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L791
毎月のリリースが目標と明言されてるので、あえて「もっと短いサイクル」とボカす意味はない気がします。
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L793
もバイル→モバイル
https://github.com/piroor/moezilla-memorial-photobook/blob/403cb77c3e1cb19d0e663889f480ccd860dc949b/article.md?plain=1#L802
Google Apps→Google Workspace
Office 365→Microsoft 365
Microsoft 365はWebアプリのみではないと思うので、少々違和感があります

**Comment by piroor** [comment]
ご指摘ありがとうございます。 138f6e4 で指摘事項を反映してみました。

> トーバルス→トーバルズ

恥ずかしながらずっと間違えて憶えていました……

> Office 365→Microsoft 365

https://learn.microsoft.com/ja-jp/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide など、O365の名称はまだ目にする事があるので、正式名称の認識が更新されていませんでした。
ありがとうございます。

> Microsoft 365はWebアプリのみではないと思うので、少々違和感があります

ご指摘の通りなので、「のWeb UI」と限定するようにしてみました。
この箇所で一応「Web UIの方」という言及の仕方をしたので、後半にもう1回ある言及については名称だけの更新としてみました。

> 現在は、Firefox、Thunderbirdの名前で収録されています。

ありがとうございます。2017年には戻っていたんですね。
社内でDebianユーザーの方から特にそういう話を聞いていなかったので、知識が更新されていませんでした。
経緯を詳しく説明するとその部分だけで別トピックになりそうなので、ざっくりした説明に簡略化してみましたが、これだとどうでしょう？

> 個人的にはFirefox for Android はしばらくFlash使えてたような…と少し混乱しました。「PC以外」より具体的に書くほうが親切かもしれません。

iPhoneと（スマホOSとしての）Androidの発表が2007年で、この箇所はそれよりもう少し前の時代をイメージしていたので、ガラケーの事を指しているという注釈を足してみました。

> Fenix移行前のFennecはネイティブUIだったと思います。

ありがとうございます。記憶違いが生じていましたが、思い出してみれば確かに、「ある程度JavaScriptで制御されたネイティブUI」でしたね。
（Bootstrapped ExtensionsでJSでゴリゴリいじれたので、そのことを失念していました。）

> ざっくり標準化団体の資料を読んだ感じ、3つではなさそうです

これも何かの原因で間違ったまま憶えてしまっていました。
Googleからの資金の話については、文脈的に自然に盛り込めなかったので、削除することにしました。

> 資金的には既に独立しているという認識で、MZLAがMozillaから独立するという話があるということでしょうか。

すみません、ここは自分の認識違いで資金的にまだ独立していないと誤解していました。

> 毎月のリリースが目標と明言されてるので、あえて「もっと短いサイクル」とボカす意味はない気がします。

これは、自分が見た記事では3ヵ月から1ヵ月へと段階的に短縮していくような話が書かれていたような記憶があったので、このように書いていました。

**Comment by hokonch** [comment]
>  記憶違いが生じていましたが、思い出してみれば確かに、「ある程度JavaScriptで制御されたネイティブUI」でしたね。
（Bootstrapped ExtensionsでJSでゴリゴリいじれたので、そのことを失念していました。）

自分は最近のことしか経験してないので詳しくないのですが、「Geckoエンジン上のUI」→「AndroidネイティブUI（XULアドオン可）」→「AndroidネイティブUI（WebExtensions限定）」→Fennec廃止でFenixに
だった記憶です。
また、Fenixの話をするなら、「モバイル版」じゃなくて「Android版」とはっきりさせたほうがいいのでは、とも思いましたが、実際最初期の非ネイティブ実装時代は他の携帯端末OSにも対応していたわけで、短く書くのは難しいですね。
補足しましたが、今の記述で要約としては自分は許容範囲かなと思います。


他、追加です。

https://github.com/piroor/moezilla-memorial-photobook/blob/138f6e4f47b6c73b40be102d422d1209fbb5789d/article.md?plain=1#L112
注釈にある佐渡氏の記事を読む限り、Netscapeはきっかけではあれど議論の当事者ではないように見えます。
https://github.com/piroor/moezilla-memorial-photobook/blob/138f6e4f47b6c73b40be102d422d1209fbb5789d/article.md?plain=1#L539
この当時はオープンWebをモバイルにという方向性で、Mozillaがプライバシーを全面に売りに出し始めたのは最近なので、ズレた記述ではと思いました。
https://github.com/piroor/moezilla-memorial-photobook/blob/138f6e4f47b6c73b40be102d422d1209fbb5789d/article.md?plain=1#L699-L700
この記述は削除してもいいんじゃないかと思いました。実状を無視して理屈だけ追えば、2/4から2/3になったことでMozillaのプレゼンスは向上した、となりそうです。
また、自分が先の指摘で参照していたのは
https://whatwg.org/working-mode#additions
ですが、Mustなのは支持で実装までは求められていません。また考慮事項は他にも複数あります。

https://github.com/piroor/moezilla-memorial-photobook/blob/138f6e4f47b6c73b40be102d422d1209fbb5789d/article.md?plain=1#L669
RustはServoのために開発されたわけではないよ、という話をどこかで読んだ記憶がある（実際歴史はRustの方が古い）ので少し引っかかりましたが、許容範囲かなという気もします。<sub>もっと細かいことを言えば、外部コントリビューター交えたオープン開発って、どこまでが「Mozillaが開発した」でどこからが「Mozillaがスポンサーになった」なのかよくわからないな、と少しモヤモヤしています。自分の認識ではRustはスポンサーに近いけれど、じゃあServoは？とか</sub>

**Comment by piroor** [comment]
> また、Fenixの話をするなら、「モバイル版」じゃなくて「Android版」とはっきりさせたほうがいいのでは、とも思いましたが、実際最初期の非ネイティブ実装時代は他の携帯端末OSにも対応していたわけで、短く書くのは難しいですね。 補足しましたが、今の記述で要約としては自分は許容範囲かなと思います。

確かにFenixはAndroidのみでした。
自分が開発合宿に参加した時はWindows Phoneであれこれやっていたのですが、いつのまにかWindows Phoneは消えてしまい……
という事があったを思いだしたので、せっかくなのでWindows Phoneのドロップにも言及してAndroidと明記するようにしてみました。


> 注釈にある佐渡氏の記事を読む限り、Netscapeはきっかけではあれど議論の当事者ではないように見えます。

佐渡氏の記事の方には記載がないのですが、記事中にある1997年4月7日の「Freeware Summit」のログ http://web.archive.org/web/20010722120541/http://lwn.net:80/1998/0409/a/summitrep.html の出席者名の箇所にはジェイミー・ザウィンスキー氏らがNetscapeから出席したと書かれていたので、当事者の一員と自分は解釈していました。

> この当時はオープンWebをモバイルにという方向性で、Mozillaがプライバシーを全面に売りに出し始めたのは最近なので、ズレた記述ではと思いました。

ありがとうございます。記述を修正しました。

> この記述は削除してもいいんじゃないかと思いました。

確かにこの部分だけ他の部分からは浮いた状態ですし、ご指摘の通り事実と異なる記述になってしまっていましたので、削除しました。

> RustはServoのために開発されたわけではないよ、という話をどこかで読んだ記憶がある（実際歴史はRustの方が古い）ので少し引っかかりましたが、

ここは自分が完全に誤解していました。ありがとうございます。
Servoに使われたことでRustも開発が進んだ、という書き方に改めました。

**Comment by hokonch** [comment]
> 佐渡氏の記事の方には記載がないのですが、記事中にある1997年4月7日の「Freeware Summit」のログ http://web.archive.org/web/20010722120541/http://lwn.net:80/1998/0409/a/summitrep.html の出席者名の箇所にはジェイミー・ザウィンスキー氏らがNetscapeから出席したと書かれていたので、当事者の一員と自分は解釈していました。

おっと、失礼しました。自分は「オープンソース」という言葉が生まれた会議の方を見ていたのですが、一般に「オープンソース」誕生の文脈では普及の変曲点と成ったFreeware summitまで語られるようですし、こちらの誤読ですね。

> Windows Phoneのドロップにも言及して

Windows Mobile版もアルファ版として開発されていたようなのですが、正式リリースがあったのはMaemo版です。
また、文章としても、唐突にWindows Phoneが出てきたという印象も受けるので、具体名を出さずボカしてもいいんじゃないでしょうか。
https://github.com/piroor/moezilla-memorial-photobook/blob/28155225a9f2685e72b6c6ffb7956ba366886fbc/article.md?plain=1#L536-L537
この文脈だと、Fenixがでてくることにやはり違和感があります。
参考：
- [Android版Firefox 11は大幅に作り直し、速く軽くする (https://xtech.nikkei.com/it/article/Interview/20120212/381062/)](https://xtech.nikkei.com/it/article/Interview/20120212/381062/)
- [フォクすけがもらえる！「生まれ変わった Android 版 Firefox キャンペーン」(http://get.foxkeh.jp/)](https://web.archive.org/web/20121010193503/http://get.foxkeh.jp/)

**Comment by hokonch** [comment]
https://github.com/piroor/moezilla-memorial-photobook/blob/28155225a9f2685e72b6c6ffb7956ba366886fbc/article.md?plain=1#L549

インドでNokiaの携帯が使われているように読めてしまう気がします（実際は激安で配られたJioPhone）。
また、StatCounterによれば、一時期はiOSを越える二番手だったものの、今では逆転され差をつけられているようです
https://gs.statcounter.com/os-market-share/mobile/india/#monthly-201802-202303

**Comment by piroor** [comment]
再度の確認ありがとうごうざいます。

Windows Phoneの言及は確かに唐突でした。「Androidに特化し、それ以外は対応しなくなった」という方向で説明を簡略化してみました。

KaiOSについても情報をありがとうございます。シェアがあったのは本当に一瞬だけだったんですね。こちらも訂正しました。

**Comment by hokonch** [comment]
> シェアがあったのは本当に一瞬だけだったんですね。

どの程度関係があるかわかりませんが、JioPhone は2017年のオリジナルモデルはKaiOSなんですが、2021年に出た上位グレードのNextはAndroid Goなんですよね。

https://github.com/piroor/moezilla-memorial-photobook/blob/3ef00a651e48f8f1e9dfea180eb865b68e8720a1/article.md?plain=1#L546

「格安の端末のOSS開発」、「格安の端末のOS」と書こうとして変換が暴走したTypoでしょうか？
文章も不自然ですし、無理に読んでもJioPhoneがシンピュータのようなオープンソースハードウェアであるかのように聞こえます。

**Comment by piroor** [comment]
しまった。「OSS開発」はIMEの補完が効いてしまった事による誤記でした（「OS」のつもりでした）。

**Comment by hokonch** [comment]
https://github.com/piroor/moezilla-memorial-photobook/blob/bdb2ffc75d03c15af53e646e9ab8617ed312609e/article.md?plain=1#L302
どうでもいいですが、ここだけ「！」が半角ですね。

たぶん書き忘れたことはもうないと思うので、閉じて大丈夫です。

**Comment by piroor** [comment]
ご指摘ありがとうございます。では、解決したものとして閉じることにします！

**Comment by hokonch** [comment]
修正対応で、整合性とれない部分が出てきてたら嫌だなと、頭から読み返したらまだいくつかでてきたので、報告しておきます。
振り回して申し訳ありません。

---
https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L7
かつて→当時
名づけた時点で消滅していたように聞こえます <sub>(誰がやってるのか知りませんが、[サイト](https://www.mozilla.gr.jp/)はまだ運営されてるんですね)</sub>。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L33
在席→在籍

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L42
埋め込みにを→埋め込みを

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L115
この時初めて→この時期初めて
「時」というと、ある一点に感じるけれど、Netscape からも参加者がいたFreeware Summitで生まれたわけではないので、ボカした方がいいでしょう。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L130
在席→在籍

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L200
CSSでの→CSSで

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L359
身軽さをを→身軽さを

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L553
行われました→行いました

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L643
~~FUELや~~
FUELが死んだのはFirefox 47です。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L651
「後述の理由からFirefoxには存在し続けてもらわなくてはならない」とありますが、後を見ても理由があまりはっきり書かれていません。
「後述」とするなら存在意義について独立した節が欲しいですし、今くらいの曖昧な説明のままにするならそもそも後述にせず「一企業の利益に左右されないオープンなWebを維持するため」とかそんなのでいいのではと思います。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L667
そう主張する検証記事もあるので問題だとまでは思いませんが、AppleはBenchmarkとったらSafariが最速だと今でも宣伝していることを補足しておきます。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L679
「自分の個人情報を人質に取られる」、定形表現として確かに用例はありますが、意味が不明瞭な表現です (ランサムウェアじゃあるまいし)。

https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L768
Firebird→Firefoxは2004年2月、Songbird v0.1が出たのは2年後の2006年2月ですから、やや不自然な記述にみえます。
そもそも、Mozillaが関わっていたわけでもない、いちXULRunnerアプリに過ぎないので、わざわざ書くことでもないような

**Comment by hokonch** [comment]
https://github.com/piroor/moezilla-memorial-photobook/pull/5/commits/65e084606b70fe6a07fe2095268232633b301f3e
https://github.com/piroor/moezilla-memorial-photobook/blob/a1f6929a8931cb98776bc8abf062f390784152e8/article.md?plain=1#L369
piroさん自身が最初におっしゃっていた「したり顔で語られる嘘」、また気づいたのでついでに修正PRに追加しておきました。
ブレイク・ロス氏、デイブ・ハイアット氏のWikipediaを見る限り、Googleにおけるキャリアの記載はありませんし
https://en.wikipedia.org/wiki/Dave_Hyatt
https://en.wikipedia.org/wiki/Blake_Ross
Ben Goodger（元Firefoxのリード開発者）とDarin Fisherとの混同でしょう。
